### ISSUE TITLE
Caching doesn't work on Windows with default settings

### ISSUE THREAD

**Issue by jkrumbiegel** [julia-actions/cache#145]
I'm on 2.0.4 and have this setup in my CI yml:

```yml
      - uses: julia-actions/setup-julia@512e2ab44f5848ea62bddd21d1ee906e989b0360
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@8608484607cba0bdb5437a7bad85d6502499d029 # v2.0.4
```

The matrix has 
```yml
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x64
```

In the windows job, post run step, I get:

```
Post job cleanup.
Post job cleanup.
      Active manifest files: 1 found
      Active artifact files: 36 found
      Active scratchspaces: 0 found
     Deleted no artifacts, repos, packages or scratchspaces
No existing caches found on ref `refs/pull/37/merge` matching restore key `julia-cache;workflow=CI;job=test;os=Windows;version=1;os=windows-latest;arch=x64;`
Post job cleanup.
Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

Is there something that needs to be configured for Windows to work that I have missed?
