### ISSUE TITLE
GitHub Actions fails if used together with IJulia Jupyter kernel

### ISSUE THREAD

**Issue by Mavoort** [julia-actions/cache#159]
The julia-cache action cannot be used together with the IJulia jupyter kernel. 
If used together with jupyter, the action fails becaue it cannot find the installed jupyter kernel for julia-1.11.

**How to reproduce:**

Create a new repo with a Jupyter notebook called `main.ipynb` containing some Julia code:

```julia
import Example
println(Example.hello("world!"))
```
Then deploy this script using the following GitHub Actions workflow:

``` yaml
on:
  workflow_dispatch:
  push:
    branches: main

name: CI

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      actions: write
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Python and then Jupyter
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install jupyter

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'

      # this doesn't work together with Jupyter.
      - name: Cache Julia Packages
        uses: julia-actions/cache@v2

      - name: Install important Julia packages
        shell: bash
        run: |
          julia -e 'using Pkg; Pkg.add("Example");'
          julia -e 'using Pkg; Pkg.add("IJulia");'

      - name: Execute main.ipynb with Jupyter
        shell: bash
        run: jupyter-execute main.ipynb
```

**Expected behaviour:** The GitHub Action should run successfully.

**Actual behaviour:** The GitHub Action fails with the following error message:
``` bash
ERROR | No such kernel named julia-1.11
Error: Process completed with exit code 1.
```

**NOTE: Since the Github action works correctly without the Julia cache, the problem must be with the Julia cache action.**

Here is a sample repo to demonstrate the problem more clearly: [Mavoort/julia_cache_action_demo](https://github.com/Mavoort/julia_cache_action_demo/tree/main)
