### ISSUE TITLE
Extend the action to packages and registry

### ISSUE THREAD

**Issue by giordano** [julia-actions/cache#2]
In some cases it may be beneficial to cache also packages (`.julia/packages`) and/or the registry (`.julia/registries`), not just artifacts.  For example I cache the registry in [`Measurements.jl`](https://github.com/JuliaPhysics/Measurements.jl/blob/b7b7c8d7ac31bcfd51088dcd9a18c0574b6d368c/.github/workflows/ci.yml#L40), and today I [enabled caching of packages](https://github.com/JuliaRegistries/General/pull/51270) in CI for the General registry.  Note that this would affect also the name of the repository/action.

Maybe we can have options to enable cachin of artifacts, packages and registy, with artifacts being the only one enabled by default?

**Comment by rikhuijzer** [comment]
Thanks for providing some extra details. Clear now. I'll add it to #1.

**Comment by rikhuijzer** [comment]
In the PR you advise against always caching the registry, especially on Windows. What would be your advice? If it is only Windows, then maybe we can enable all caching by default and disable caching the registry for Windows by default?

Or would you advice having inputs as follows:
```
inputs:
  cache-artifacts:
    description: 'Whether to cache artifacts'
    default: 'true'
  cache-packages:
    description: 'Whether to cache packages'
    default: 'true'
  cache-registry:
    description: 'Whether to cache the registry'
    default: 'false'
```
