### ISSUE TITLE
Merge with `setup-julia`?

### ISSUE THREAD

**Issue by MilesCranmer** [julia-actions/cache#34]
Could this be included inside the `setup-julia` action? For example:
```yml
- uses: julia-actions/setup-julia
  with:
    version: 1.8.2
    cache: true
```
and inside that `cache` dict, you could have the options available here. This is also what `actions/setup-python` has started to do.

I do think it should still remain a separate action, since this repo can be useful for caching the conda-forge version of Julia.
