### ISSUE TITLE
Cache datadeps

### ISSUE THREAD

**Issue by aviks** [julia-actions/cache#40]
The [DataDeps.jl](https://github.com/oxinabox/DataDeps.jl) package is useful in many situations that Artifacts do not handle. It would be nice to cache automatically  the `.julia/datadeps` directory that this package uses for it's storage.

**Comment by rikhuijzer** [comment]
Could this maybe be solved on the `DataDeps.jl` side by adding to the `DataDeps.jl` README that people can use the following:

```yaml
      - uses: actions/cache@v3
        with:
          path: '~/.julia/datadeps'
          key: 'datadeps-${{ hashFiles('src') }}'
          restore-keys: |
            datadeps-
```

Unlike the default Julia cache action (see below), this block will update the cache every time that any file in `src` changes and it will restore any earlier saved cache as long as it starts with `datadeps-`. Note that there is a risk of running out of allowed cache space especially when `DataDeps.jl` is used for large files.

The default Julia cache action looked something like ([source](https://github.com/JuliaData/DataFrames.jl/blob/f76c6972a55cd94978b750e8631d513ae638d09b/.github/workflows/ci.yml)):

```yaml
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
```
