### ISSUE TITLE
Non-unique cache key when using objects in job matrix

### ISSUE THREAD

**Issue by omus** [julia-actions/cache#87]
A GitHub action job matrix supports defining YAML objects as part of the matrix specification:
```yaml
strategy:
  matrix:
    pkg:
      - name: A
        dir: A.jl
      - name: B
        dir: B.jl
    version:
      - "1"
    runs-on:
      - ubuntu-latest
    arch:
      - x64
```
When utilizing this pattern with `julia-actions/cache` the resulting default generated cache key is `julia-cache-workflow-job-Object-1-ubuntu-latest-x64-Linux-...` when running for package A and package B. This is problematic as these keys are not unique which means we're only storing the cached depot information for the last run job.
